# Generated by Django 5.0.6 on 2024-06-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
