# Generated by Django 5.0.6 on 2024-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddress_email_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_no',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
