export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'


export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST'
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS'
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL'

export const  SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS'
export const  SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE'
export const  SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_FAILURE'
export const SEARCH_PRODUCTS_CLEAR = 'SEARCH_PRODUCTS_CLEAR'
   